steps:

- id: build&push
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t fedimersni/gdg-sousse:latest .
    docker push fedimersni/gdg-sousse:latest



- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: sh
  args:
  - '-c'
  - |

      gcloud run deploy gdg-sousse \
      --region=europe-west1 \
      --allow-unauthenticated \
      --image fedimersni/gdg-sousse:latest



options:
  logging: CLOUD_LOGGING_ONLY